// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitPlayer() Player {
	mission := NewMission()
	player := mission.Player
	return player
}

func InitMonster() Monster {
	mission := NewMission()
	monster := mission.Monster
	return monster
}
