// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
)

const getWriter = `-- name: GetWriter :one
SELECT id, bio FROM writers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWriter(ctx context.Context, id int32) (Writer, error) {
	row := q.db.QueryRowContext(ctx, getWriter, id)
	var i Writer
	err := row.Scan(&i.ID, &i.Bio)
	return i, err
}
