// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAuthorStmt, err = db.PrepareContext(ctx, createAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuthor: %w", err)
	}
	if q.deleteAuthorStmt, err = db.PrepareContext(ctx, deleteAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAuthor: %w", err)
	}
	if q.getAuthorStmt, err = db.PrepareContext(ctx, getAuthor); err != nil {
		return nil, fmt.Errorf("error preparing query GetAuthor: %w", err)
	}
	if q.listAuthorsStmt, err = db.PrepareContext(ctx, listAuthors); err != nil {
		return nil, fmt.Errorf("error preparing query ListAuthors: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAuthorStmt != nil {
		if cerr := q.createAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuthorStmt: %w", cerr)
		}
	}
	if q.deleteAuthorStmt != nil {
		if cerr := q.deleteAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAuthorStmt: %w", cerr)
		}
	}
	if q.getAuthorStmt != nil {
		if cerr := q.getAuthorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAuthorStmt: %w", cerr)
		}
	}
	if q.listAuthorsStmt != nil {
		if cerr := q.listAuthorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAuthorsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db               DBTX
	tx               *sql.Tx
	createAuthorStmt *sql.Stmt
	deleteAuthorStmt *sql.Stmt
	getAuthorStmt    *sql.Stmt
	listAuthorsStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:               tx,
		tx:               tx,
		createAuthorStmt: q.createAuthorStmt,
		deleteAuthorStmt: q.deleteAuthorStmt,
		getAuthorStmt:    q.getAuthorStmt,
		listAuthorsStmt:  q.listAuthorsStmt,
	}
}
