// Code generated by file2byteslice. DO NOT EDIT.

package resources

var ConfigJson = []byte("{\r\n  \"screenWidth\": 640,\r\n  \"screenHeight\": 480,\r\n  \"title\": \"外星人入侵\",\r\n  \"bgColor\": {\r\n    \"r\": 230,\r\n    \"g\": 230,\r\n    \"b\": 230,\r\n    \"a\": 255\r\n  },\r\n  \"shipSpeedFactor\": 3,\r\n  \"bulletWidth\": 3,\r\n  \"bulletHeight\": 15,\r\n  \"bulletSpeedFactor\": 2,\r\n  \"bulletColor\": {\r\n    \"r\": 80,\r\n    \"g\": 80,\r\n    \"b\": 80,\r\n    \"a\": 255\r\n  },\r\n  \"maxBulletNum\": 10,\r\n  \"bulletInterval\": 100,\r\n  \"alienSpeedFactor\": 1,\r\n  \"titleFontSize\": 36,\r\n  \"fontSize\": 24,\r\n  \"smallFontSize\": 12\r\n}")
