// Code generated by qtc from "type.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/type.qtpl:1
package templates

//line templates/type.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/type.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/type.qtpl:1
func StreamTypes(qw422016 *qt422016.Writer, a int, b float64, c []byte, d string) {
//line templates/type.qtpl:1
	qw422016.N().S(`
  int: `)
//line templates/type.qtpl:2
	qw422016.N().D(a)
//line templates/type.qtpl:2
	qw422016.N().S(`, float64: `)
//line templates/type.qtpl:2
	qw422016.N().FPrec(b, 2)
//line templates/type.qtpl:2
	qw422016.N().S(`, bytes: `)
//line templates/type.qtpl:2
	qw422016.E().Z(c)
//line templates/type.qtpl:2
	qw422016.N().S(`, string with quotes: `)
//line templates/type.qtpl:2
	qw422016.E().Q(d)
//line templates/type.qtpl:2
	qw422016.N().S(`, string without quotes: `)
//line templates/type.qtpl:2
	qw422016.E().J(d)
//line templates/type.qtpl:2
	qw422016.N().S(`.
`)
//line templates/type.qtpl:3
}

//line templates/type.qtpl:3
func WriteTypes(qq422016 qtio422016.Writer, a int, b float64, c []byte, d string) {
//line templates/type.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/type.qtpl:3
	StreamTypes(qw422016, a, b, c, d)
//line templates/type.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line templates/type.qtpl:3
}

//line templates/type.qtpl:3
func Types(a int, b float64, c []byte, d string) string {
//line templates/type.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/type.qtpl:3
	WriteTypes(qb422016, a, b, c, d)
//line templates/type.qtpl:3
	qs422016 := string(qb422016.B)
//line templates/type.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/type.qtpl:3
	return qs422016
//line templates/type.qtpl:3
}
