// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitMission(name string) (Mission, func(), error) {
	player, cleanup, err := NewPlayer(name)
	if err != nil {
		return Mission{}, nil, err
	}
	monster := NewMonster()
	mission := NewMission(player, monster)
	return mission, func() {
		cleanup()
	}, nil
}
