// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEndingA(name string) EndingA {
	player := NewPlayer(name)
	monster := NewMonster()
	endingA := NewEndingA(player, monster)
	return endingA
}

func InitEndingB(name string) EndingB {
	player := NewPlayer(name)
	monster := NewMonster()
	endingB := NewEndingB(player, monster)
	return endingB
}

// wire.go:

var monsterPlayerSet = wire.NewSet(NewMonster, NewPlayer)
