// Code generated by qtc from "score.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/score.qtpl:1
package templates

//line templates/score.qtpl:1
import "fmt"

//line templates/score.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/score.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/score.qtpl:2
func StreamScoreList(qw422016 *qt422016.Writer, name2score map[string]int) {
//line templates/score.qtpl:2
	qw422016.N().S(`
  `)
//line templates/score.qtpl:3
	for name, score := range name2score {
//line templates/score.qtpl:3
		qw422016.N().S(`
    `)
//line templates/score.qtpl:4
		qw422016.E().S(fmt.Sprintf("%s: score-%d rank-%s", name, score, Rank(score)))
//line templates/score.qtpl:4
		qw422016.N().S(`
  `)
//line templates/score.qtpl:5
	}
//line templates/score.qtpl:5
	qw422016.N().S(`
`)
//line templates/score.qtpl:6
}

//line templates/score.qtpl:6
func WriteScoreList(qq422016 qtio422016.Writer, name2score map[string]int) {
//line templates/score.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/score.qtpl:6
	StreamScoreList(qw422016, name2score)
//line templates/score.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line templates/score.qtpl:6
}

//line templates/score.qtpl:6
func ScoreList(name2score map[string]int) string {
//line templates/score.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/score.qtpl:6
	WriteScoreList(qb422016, name2score)
//line templates/score.qtpl:6
	qs422016 := string(qb422016.B)
//line templates/score.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/score.qtpl:6
	return qs422016
//line templates/score.qtpl:6
}
