// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitMission(m MonsterParam, p PlayerParam) Mission {
	player := NewPlayer(p)
	monster := NewMonster(m)
	mission := NewMission(player, monster)
	return mission
}
